'use client'

import { useEffect, useState } from 'react'
import { FileDown, Settings2 } from 'lucide-react'
import { toast } from 'sonner'
import { formatNaira } from '@/lib/utils/format'

type InvoiceOrder = { order_number: string; design_description: string | null; total_price?: number | null; estimated_delivery_date?: string | null; created_at: string }
type InvoiceSettings = { businessName: string; phone: string; email: string; address: string; paymentInstructions: string }
const clean = (value: string) => value.replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character] || character))

export function InvoiceActions({ order, customerName, shopName, shopId }: { order: InvoiceOrder; customerName: string; shopName?: string; shopId: string }) {
  const storageKey = `tailorpal-invoice-${shopId}`
  const [showSettings, setShowSettings] = useState(false)
  const [settings, setSettings] = useState<InvoiceSettings>({ businessName: shopName || 'My Atelier', phone: '', email: '', address: '', paymentInstructions: 'Please use your order number as the payment reference.' })
  useEffect(() => { const saved = localStorage.getItem(storageKey); if (saved) setSettings(JSON.parse(saved) as InvoiceSettings) }, [storageKey])
  const save = () => { localStorage.setItem(storageKey, JSON.stringify(settings)); setShowSettings(false); toast.success('Invoice details saved on this device') }
  const printInvoice = () => {
    const date = new Date(order.created_at).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
    const due = order.estimated_delivery_date ? new Date(order.estimated_delivery_date).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' }) : 'To be confirmed'
    const popup = window.open('', '_blank', 'noopener,noreferrer')
    if (!popup) { toast.error('Please allow pop-ups to create the invoice'); return }
    popup.document.write(`<!doctype html><html><head><title>Invoice ${clean(order.order_number)}</title><style>body{font-family:Arial,sans-serif;color:#211c18;margin:0;padding:48px;background:#fcfbf8}.card{max-width:760px;margin:auto;background:#fff;padding:48px;border:1px solid #e5ded4}.top{display:flex;justify-content:space-between;border-bottom:3px solid #d97b2b;padding-bottom:28px}.muted{color:#756b61;font-size:13px}.label{font-size:11px;text-transform:uppercase;letter-spacing:1.5px;color:#756b61;font-weight:bold}.amount{font-size:28px;font-weight:bold}.line{border-top:1px solid #e5ded4;margin:28px 0;padding-top:20px;display:flex;justify-content:space-between}@media print{body{padding:0;background:#fff}.card{border:0}}</style></head><body><main class="card"><section class="top"><div><div class="label">Bespoke atelier</div><h1>${clean(settings.businessName || shopName || 'My Atelier')}</h1><p class="muted">${clean(settings.address)}<br>${clean(settings.phone)} ${settings.email ? `· ${clean(settings.email)}` : ''}</p></div><div><div class="label">Invoice</div><h2>#${clean(order.order_number)}</h2><p class="muted">Issued ${clean(date)}<br>Due: ${clean(due)}</p></div></section><section style="margin-top:30px"><div class="label">Bill to</div><h3>${clean(customerName)}</h3></section><section class="line"><div><div class="label">Commission</div><strong>${clean(order.design_description || 'Custom Bespoke Outfit')}</strong></div><div style="text-align:right"><div class="label">Total</div><div class="amount">${clean(formatNaira(order.total_price))}</div></div></section><section><div class="label">Payment instructions</div><p class="muted">${clean(settings.paymentInstructions)}</p></section><p class="muted" style="margin-top:50px">Thank you for choosing ${clean(settings.businessName || shopName || 'our atelier')}.</p></main><script>window.onload=()=>window.print()</script></body></html>`)
    popup.document.close()
  }
  return <div className="space-y-2"><div className="flex gap-2"><button onClick={printInvoice} className="flex-1 h-11 rounded-xl bg-brand-ink hover:bg-brand-charcoal text-white text-xs font-bold flex items-center justify-center gap-2"><FileDown size={15} />Create PDF Invoice</button><button onClick={() => setShowSettings((value) => !value)} className="h-11 px-3 rounded-xl border border-brand-border text-brand-ink" title="Customise invoice"><Settings2 size={15} /></button></div>{showSettings && <div className="rounded-xl border border-brand-border bg-brand-cream/50 p-3 grid sm:grid-cols-2 gap-2"><input value={settings.businessName} onChange={(event) => setSettings({ ...settings, businessName: event.target.value })} placeholder="Business name" className="h-9 rounded-lg border border-brand-border px-2 text-xs"/><input value={settings.phone} onChange={(event) => setSettings({ ...settings, phone: event.target.value })} placeholder="Phone" className="h-9 rounded-lg border border-brand-border px-2 text-xs"/><input value={settings.email} onChange={(event) => setSettings({ ...settings, email: event.target.value })} placeholder="Email" className="h-9 rounded-lg border border-brand-border px-2 text-xs"/><input value={settings.address} onChange={(event) => setSettings({ ...settings, address: event.target.value })} placeholder="Business address" className="h-9 rounded-lg border border-brand-border px-2 text-xs"/><input value={settings.paymentInstructions} onChange={(event) => setSettings({ ...settings, paymentInstructions: event.target.value })} placeholder="Payment instructions" className="h-9 rounded-lg border border-brand-border px-2 text-xs sm:col-span-2"/><button onClick={save} className="sm:col-span-2 h-9 rounded-lg bg-brand-gold text-white text-xs font-bold">Save invoice details</button></div>}</div>
}
