'use client'
import { useEffect, useMemo, useState } from 'react'
import { useParams } from 'next/navigation'
import { Download, BarChart3 } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'
import { formatNaira } from '@/lib/utils/format'
type Order={id:string;order_number:string;design_description:string|null;status:string;total_price:number|null;estimated_delivery_date:string|null;deposit_amount:number|null;created_at:string}
type Expense={amount:number;expense_date:string}
type Task={id:string;status:string;assigned_staff_id:string|null;estimated_minutes:number|null;production_time_entries:{started_at:string;ended_at:string|null}[]}
const dateKey=(date:string)=>new Date(date).toISOString().slice(0,10)
export function AnalyticsPageContent(){const{shopId}=useParams<{shopId:string}>();const db=createClient();const[orders,setOrders]=useState<Order[]>([]);const[expenses,setExpenses]=useState<Expense[]>([]);const[tasks,setTasks]=useState<Task[]>([]);const[range,setRange]=useState('30')
 useEffect(()=>{const load=async()=>{const[a,b,c]=await Promise.all([db.from('orders').select('id,order_number,design_description,status,total_price,estimated_delivery_date,deposit_amount,created_at').eq('shop_id',shopId),db.from('business_expenses').select('amount,expense_date').eq('shop_id',shopId),db.from('production_tasks').select('id,status,assigned_staff_id,estimated_minutes,production_time_entries(started_at,ended_at)').eq('shop_id',shopId)]);setOrders((a.data||[])as Order[]);setExpenses((b.data||[])as Expense[]);setTasks((c.data||[])as Task[])};void load()},[shopId])
 const stats=useMemo(()=>{const start=new Date();start.setDate(start.getDate()-Number(range));const inRange=orders.filter(o=>new Date(o.created_at)>=start);const inRangeExpenses=expenses.filter(e=>new Date(e.expense_date)>=start);const revenue=inRange.reduce((s,o)=>s+Number(o.total_price||0),0);const costs=inRangeExpenses.reduce((s,e)=>s+Number(e.amount||0),0);const today=dateKey(new Date().toISOString());const overdue=orders.filter(o=>o.status!=='delivered'&&o.status!=='cancelled'&&o.estimated_delivery_date&&o.estimated_delivery_date<today).length;const atRisk=orders.filter(o=>o.status==='pending'||o.status==='in_progress').filter(o=>o.estimated_delivery_date&&new Date(o.estimated_delivery_date).getTime()-Date.now()<3*86400000).length;const outstanding=orders.reduce((s,o)=>s+Math.max(0,Number(o.total_price||0)-Number(o.deposit_amount||0)),0);const completed=tasks.filter(t=>t.status==='done').length;const timed=tasks.filter(t=>t.status==='done').flatMap(t=>t.production_time_entries).filter(e=>e.ended_at);const average=timed.length?timed.reduce((s,e)=>s+(new Date(e.ended_at!).getTime()-new Date(e.started_at).getTime())/60000,0)/timed.length:0;const types=Object.entries(inRange.reduce<Record<string,number>>((map,o)=>{const key=(o.design_description||'Other').split(/[,-]/)[0];map[key]=(map[key]||0)+1;return map},{})).sort((a,b)=>b[1]-a[1]);return{revenue,costs,profit:revenue-costs,overdue,atRisk,outstanding,completion:tasks.length?Math.round(completed/tasks.length*100):0,average,types}},[orders,expenses,tasks,range])
 const exportReport=()=>{const rows=[['Metric','Value'],['Revenue',String(stats.revenue)],['Expenses',String(stats.costs)],['Profit',String(stats.profit)],['Overdue orders',String(stats.overdue)],['At-risk orders',String(stats.atRisk)],['Outstanding balances',String(stats.outstanding)],['Task completion',`${stats.completion}%`],['Average completed task minutes',String(Math.round(stats.average))],...stats.types.map(([type,count])=>[`Garment type: ${type}`,String(count)])];const blob=new Blob([rows.map(row=>row.map(value=>`"${value.replace(/"/g,'""')}"`).join(',')).join('\n')],{type:'text/csv'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`tailorpal-report-${range}-days.csv`;link.click();URL.revokeObjectURL(url)}
 const cards=[['Revenue',formatNaira(stats.revenue)],['Expenses',formatNaira(stats.costs)],['Profit',formatNaira(stats.profit)],['Overdue orders',String(stats.overdue)],['Orders at risk',String(stats.atRisk)],['Outstanding balances',formatNaira(stats.outstanding)],['Task completion',`${stats.completion}%`],['Average task time',stats.average?`${Math.round(stats.average)} min`:'No timed tasks']]
 return <div className="p-4 lg:p-8 max-w-7xl mx-auto space-y-6"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h1 className="font-display text-3xl text-brand-ink flex gap-2 items-center"><BarChart3 className="text-brand-gold"/>Business insights</h1><p className="text-sm text-brand-stone mt-1">Simple numbers from your orders, expenses, and workshop tasks.</p></div><div className="flex gap-2"><select value={range} onChange={e=>setRange(e.target.value)} className="h-10 rounded-xl border border-brand-border px-3 text-sm"><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="365">Last 12 months</option></select><button onClick={exportReport} className="h-10 rounded-xl bg-brand-ink px-4 text-xs font-bold text-white flex items-center gap-2"><Download size={14}/>Export CSV</button></div></div><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3">{cards.map(([label,value])=><div key={label} className="rounded-2xl border border-brand-border bg-white p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-brand-stone">{label}</p><p className="font-display text-2xl text-brand-ink mt-1">{value}</p></div>)}</div><section className="rounded-2xl border border-brand-border bg-white p-5"><h2 className="font-bold text-brand-ink">Most requested garment types</h2>{stats.types.length?<div className="mt-3 space-y-2">{stats.types.map(([type,count])=><div key={type} className="flex justify-between text-sm"><span>{type}</span><b>{count} order{count===1?'':'s'}</b></div>)}</div>:<p className="mt-3 text-sm text-brand-stone">Create orders to see your most requested styles.</p>}</section></div>}
